apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 5050
      protocol: TCP
      targetPort: 5050
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer